Add ESLint to Project
MarkBind/markbind-cli pull request #14
Opened 2018-01-16 14:44 UTC by nicholaschuayunzhi

Adds ESLint and its lodash plugin as a dev dependency. --fix command not executed yet. The eslintrc file was taken from https://github.com/MarkBind/markbind/blob/master/.eslintrc.js

2018-01-17 17:15 UTC, Gisonrg commented
Nice one! Can't wait to fix all the style issues in the project :D

Before I merge this, do you think we should use an existing style standard for our eslint?
I am thinking about using either https://github.com/airbnb/javascript or https://github.com/google/eslint-config-google

Feel free to discuss with the team to choose a standard you all agreed on.

2018-01-18 06:58 UTC, nicholaschuayunzhi commented
I've used airbnb before. I would prefer airbnb as their docs have the eslint rules which we can ctrl f easily to see an example of.

2018-01-18 07:06 UTC, damithc commented
The common standards for our projects (open for updates) https://github.com/oss-generic/process/blob/master/docs/CodingStandards.adoc

2018-01-18 07:12 UTC, Gisonrg commented
Let's use the airbnb preset and modified based on our standard then :P

 @nicholaschuayunzhi Can you help us set up the eslint as discussed?

2018-01-18 07:14 UTC, acjh commented
> The common standards for our projects (open for updates) https:\//github.com/oss-generic/process/blob/master/docs/CodingStandards.adoc
>> If a topic is not covered in this document, refer to airbnb JavaScript Style Guide

airbnb it is! Also, [teammates-eslint.yml](https://github.com/TEAMMATES/teammates/blob/60a9efd3b5f1c7e1e0d035160bf9ed1f53e5d800/static-analysis/teammates-eslint.yml).

2018-01-18 07:14 UTC, nicholaschuayunzhi commented
Okay I'll work on it. Need to do some research first.

Also do you want it to be standardized across all the modules?

2018-01-18 07:17 UTC, Gisonrg commented
Nice, take you time. Let's start from `markbind-cli` first, then extend it to `markbind` (vue modules has different style standard).

2018-01-19 08:02 UTC, nicholaschuayunzhi commented
Changed rules wrt to [oss-generic coding standards](https://docs.google.com/document/d/1gZ6WG6HBTJYHAtVkz9kzi_SUuzfXqzO-SvFnLuag2xM/pub?embedded=true)

Rules that can't be modified with existing eslint rules:
- Constants named in screaming snake case
- Prefer higher-level breaks to lower-level breaks. In the example below, the first is preferred, since the break occurs outside the parenthesized expression, which is at a higher level.
- suggestion for ternary expression
![image](https://user-images.githubusercontent.com/22221132/35140362-e84fb3b0-fd31-11e7-8ea6-7037525153cb.png)

Read up on writing custom rules. Is it worth the time? Anyone with experience? Also will add to dev guide on how to set up eslint.

2018-01-20 08:10 UTC, nicholaschuayunzhi commented
I've updated the eslint config as discussed. Disabled func-names rule and added line break style.

2018-01-20 15:12 UTC, acjh requested changes

2018-01-20 15:12 UTC, acjh commented on .eslintrc.js
> +    "func-names": "off",
Alphabetical (ascii) order:
- `func-names` before `function-paren-newline`
- `FunctionDeclaration` before `FunctionExpression`

2018-01-20 15:12 UTC, acjh commented on .eslintrc.js
> +        "MemberExpression": 1,
`1` seems to be the default in [indent](https://eslint.org/docs/rules/indent.html) and is not overridden by [airbnb](https://github.com/airbnb/javascript).

2018-01-20 15:16 UTC, acjh commented
I took a while to understand why some choices were made.

Perhaps we should document this in the Wiki, together with the setup instructions.

2018-01-20 15:38 UTC, acjh requested changes

2018-01-20 15:38 UTC, acjh commented on .eslintrc.js
> +        "FunctionDeclaration": { "parameters": "first" },
Alphabetical (ascii) order:
- `FunctionDeclaration` before `FunctionExpression`

2018-01-20 15:39 UTC, acjh commented
> Perhaps we should document this in the Wiki, together with the setup instructions.

Maybe *not* with the setup instructions (seems out-of-place in the [Developer Guide](https://github.com/MarkBind/markbind-cli/wiki/Developer-Guide)).

2018-01-20 15:40 UTC, nicholaschuayunzhi commented
I'm working on the explanation in a separate gist i can link to in the dev guide.

2018-01-20 16:24 UTC, nicholaschuayunzhi commented
I've removed ArrayExpression option in indent as the default option (1) account for aligning elements based on 2 spaces of indentation.

I've added the `"array-bracket-newline": ["error", { "multiline": true }],` to be consistent with airbnb's
`object-curly-newline` rule, as well as to prevent such code from passing which is not wanted based on nus oss js standard.
```
let array = [1,
  2,
  3,]
```

2018-01-20 16:29 UTC, nicholaschuayunzhi commented
I've added a [gist](https://gist.github.com/nicholaschuayunzhi/bfe53dbb5f1a0f02d545d55956f9ab7e) for the explanation to the developer guide.

2018-01-20 16:35 UTC, acjh commented
> to be consistent with airbnb's `object-curly-newline` rule

I don't see this 🤔

2018-01-20 16:36 UTC, acjh requested changes

2018-01-20 16:36 UTC, acjh commented on .eslintrc.js
> +        "CallExpression": { "arguments": "first" } ,
Remove space before comma.

2018-01-20 16:38 UTC, acjh commented
> I've added a gist for the explanation to the developer guide.

Nice. This can be a page in the Wiki. Let's [create a sidebar](https://help.github.com/articles/creating-a-sidebar/); the current pages need categorisation anyway.

2018-01-20 17:29 UTC, nicholaschuayunzhi commented
> to be consistent with airbnb's object-curly-newline rule
>>I don't see this 🤔

Oh dear, i think i saw wrongly. But the rationale still stands to prevent the below from happening.
```
let array = [1,
  2,
  3,]
```

Weird though, my linter is firing off that error. Could it be a default rule? https://eslint.org/docs/rules/object-curly-newline

2018-01-21 02:43 UTC, acjh commented
Both rules seem to be `{ "multiline": true }` by default.

2018-01-21 04:23 UTC, nicholaschuayunzhi commented
Seems when i do not specify array-bracket-newline, it does not fire off any linting error.
![image](https://user-images.githubusercontent.com/22221132/35190814-e41128ea-fea5-11e7-856b-5814eb2ca9d0.png)

Need to look into it further.

2018-01-21 04:30 UTC, nicholaschuayunzhi commented
In the eslint docs for both rules, seems like [array-bracket-newline](https://eslint.org/docs/rules/array-bracket-newline) is not enabled by default.  
![image](https://user-images.githubusercontent.com/22221132/35190842-cf8fac1a-fea6-11e7-8049-55dc81ba1b7a.png)



However for [object-curly-newline](https://eslint.org/docs/rules/object-curly-newline). It is enabled.
![image](https://user-images.githubusercontent.com/22221132/35190840-a7e8302e-fea6-11e7-842b-134d5913f12c.png)

So i think we should still have the `array-bracket-newline` rule.

2018-01-21 04:40 UTC, acjh commented
Nice catch.

2018-01-21 04:42 UTC, nicholaschuayunzhi commented
I still find it weird though, according to [user guide](https://eslint.org/docs/rules/), no rules are enabled by default, but the docs seem to say otherwise.

2018-01-21 04:51 UTC, nicholaschuayunzhi commented
Ok i think i got it, they disabled `array-bracket-newline` and enabled `object-curly-newline` in airbnb-base preset.

https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js

2018-01-21 05:12 UTC, nicholaschuayunzhi commented
Okay I think it should be ready for merge. Note that operator-linebreak is manually enabled as [airbnb-base package with enabled operator-linebreak rule is not published yet](https://github.com/airbnb/javascript/commit/6e1f11185d95432ba90a647efc027bd32983f17d)

I've also removed the line endings rule as airbnb-base already checks for unix endings

2018-01-21 17:30 UTC, Gisonrg commented
LGTM, feel free to merge this @acjh

2018-01-21 18:14 UTC, acjh approved these changes

2018-01-21 18:14 UTC, merged

2018-01-21 18:15 UTC, acjh commented
@nicholaschuayunzhi Thanks for your contribution!

2018-01-22 02:35 UTC, acjh commented
@nicholaschuayunzhi Can you create a PR to apply `--fix`?

2018-01-22 06:18 UTC, nicholaschuayunzhi commented
@acjh  Will do!